'use strict';
// Operational evidence only: no patient records or statutory register replacement.
const ASSURANCE_SOURCES={
 governance:'https://www.psi.ie/registration/pharmacies/superintendent-and-supervising-pharmacists',
 assessment:'https://www.psi.ie/inspections/pharmacy-assessment-system',
 drugs:'https://www.psi.ie/practice-supports/guidance-and-guidelines-pharmacists-and-pharmacies/guidelines-disposal-medicinal',
 services:'https://www.psi.ie/practice-supports/guidance-and-guidelines-pharmacists-and-pharmacies/guidelines-common-conditions-service',
 pcrs:'https://healthservice.hse.ie/staff/information-healthcare-workers/pcrs/primary-care-contractor-handbooks/',
 privacy:'https://dataprotection.ie/en/dpc-guidance/guidance-on-the-use-of-cctv',
 safety:'https://www.hsa.ie/eng/topics/managing_health_and_safety/safety_statement_and_risk_assessment/',
 medicines:'https://www.hpra.ie/regulation/human-medicine/wholesalers-and-retailers'
};
const REVIEW_PACKS=[
 {id:'psi',title:'Pharmacy self-assessment',source:'assessment',items:['Named governance roles and pharmacist cover evidence','Registration renewal and material changes reviewed','Current SOPs, local applicability and acknowledgements','Prescription assessment, counselling and referral arrangements','Storage, sourcing, expiry and recall evidence','Controlled drug procedures and records reviewed','Consultation area, privacy and service arrangements','Staff competence, handover and improvement actions']},
 {id:'cd',title:'Controlled drugs',source:'drugs',items:['Safe custody and access arrangements reviewed','Reconciliation checked against the designated statutory records','Discrepancies investigated and escalated to the pharmacist','Prescription validity checks evidenced in the designated system','Expired and returned stock segregated appropriately','Destruction evidence checked for the relevant schedule and stock type']},
 {id:'stock',title:'Medicines handling',source:'medicines',items:['Supplier authorisations and sourcing evidence checked','Cold chain records and excursion decisions reviewed','FMD alerts and unresolved exceptions reviewed in the designated system','Expiry checks, stock rotation and segregated stock reviewed','Recall scope, quantities, returns and branch confirmation reviewed','Shortage issues and pharmacist decisions referenced']},
 {id:'pcrs',title:'PCRS claims assurance',source:'pcrs',items:['Applicable schemes, current handbook and circulars identified','Sample selected and source-system claim references recorded','Eligibility and prescription evidence checked','Supporting paperwork and supply/owing records checked','Submission deadlines, rejections and queries reviewed','Corrections, recovery queries and follow-up evidence recorded']},
 {id:'otc',title:'Non-prescription medicines',source:'assessment',items:['Current codeine and pseudoephedrine procedures accessible','Staff consultation and pharmacist referral competence reviewed','Privacy and consultation area arrangements checked','Exceptions, refused supply and concerns referenced appropriately']},
 {id:'privacy',title:'Privacy and records',source:'privacy',items:['Access permissions and leaver access reviewed','Record retention and disposal arrangements reviewed by record type','Privacy notices, information sharing and processor arrangements reviewed','CCTV purpose, access, signage and retention reviewed','Breach reporting and subject access procedures tested']},
 {id:'safety',title:'Workplace safety',source:'safety',items:['Site-specific safety statement and risk assessments current','Lone working, violence/aggression and emergency arrangements reviewed','Fire, first aid, sharps and hazardous substances controls reviewed','Staff training and equipment checks evidenced','Accidents, hazards and outstanding actions reviewed']},
 {id:'services',title:'Clinical service readiness',source:'services',items:['Service selected and current approved protocol identified','Pharmacist authorisation, training and competence verified','Consultation space, equipment and emergency arrangements checked','Consent, assessment, referral and clinical record system confirmed','Storage, waste and infection prevention arrangements checked','Applicable claiming and quality review arrangements confirmed']}
];
const COMPETENCIES=['Local induction / locum handover','Errors and near misses','Cold chain','Controlled drugs','Codeine / pseudoephedrine','Privacy and records','Workplace safety / lone working','Vaccination','Emergency contraception','Common Conditions Service','Prescription extension / other service','Professional registration / CPD evidence'];
const EXCEPTIONS=['Controlled drug discrepancy','FMD alert','Medicine shortage','Expiry / quarantine','Supplier / delivery concern','Recall follow-up','PCRS claim query','Privacy incident','Pharmacist cover gap'];
function assuranceState(){return state.assurance||(state.assurance={version:1,governance:[],cover:[],reviews:[],exceptions:[],competence:[]});}
function assureField(name,label,type='text',value='',required=true){return `<label for="as-${name}">${esc(label)}</label><input id="as-${name}" name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='text'?'maxlength="180"':''}>`;}
function assureNote(name,label){return `<label for="as-${name}">${esc(label)}</label><textarea id="as-${name}" name="${name}" required maxlength="2500"></textarea>`;}
function assureSelect(name,label,options){return `<label for="as-${name}">${esc(label)}</label><select id="as-${name}" name="${name}" required><option value="">Choose</option>${options.map(x=>`<option>${esc(x)}</option>`).join('')}</select>`;}
function requireSite(){if(state.site==='all'){toast('Choose a pharmacy first.');return false;}return true;}
function requireReviewer(){if(!reviewer()){toast('Use a Pharmacist or Group admin demo view.');return false;}return requireSite();}
const assuranceNotice='<p class="notice">Prototype evidence workflows. Use fictional names and references only; keep patient, prescription and statutory records in their designated systems.</p>';
function asStatus(r){const open=state.actions.some(a=>a.source===r.id&&a.status!=='Closed');return open?'Follow-up open':r.next&&r.next<DEMO_DATE?'Review overdue':'Recorded';}
function governanceStatus(g){if(!g)return 'Not recorded';if(g.renewal<DEMO_DATE)return 'Renewal overdue';return 'Recorded';}
function assurancePanel(){
 const a=assuranceState(),g=a.governance.filter(x=>state.site==='all'||x.site===state.site),reviews=scoped(a.reviews);
 return `<section class="section"><div class="section-title"><h2>Branch assurance</h2></div><div class="grid two"><div class="card"><h3>Governance & cover</h3><p class="small muted section">Named responsibilities, registration renewal and pharmacist handovers.</p><div class="buttons section">${btn('Governance records','assure:governance','secondary')}${btn('Record cover','assure:cover','secondary')}</div><p class="small muted section">${g.length} of ${state.site==='all'?activeSites().length:1} pharmacies have a governance record.</p></div><div class="card"><h3>Evidence reviews</h3><p class="small muted section">Review the records, identify gaps and assign the next step.</p><div class="buttons section">${btn('Start a review','assure:review','')}${btn('View reviews','assure:reviews','secondary')}</div><p class="small muted section">${reviews.length} recorded · ${reviews.filter(r=>asStatus(r)!=='Recorded').length} need follow-up.</p></div></div></section>`;
}
function governanceDialog(){
 const a=assuranceState();if(state.site==='all'){
 modal('Governance across pharmacies',`<div class="assurance-list">${activeSites().map(s=>{const g=a.governance.find(g=>g.site===s.id);return `<div class="row"><div class="row-content"><h3>${esc(s.name)}</h3><p>${g?esc(g.superintendent)+' / '+esc(g.supervising):'Named roles and renewal evidence not recorded'}</p></div>${badge(governanceStatus(g),!g?'gray':g.renewal<DEMO_DATE?'red':'gray')}</div>`;}).join('')}</div><p class="field-note">Select a pharmacy to review or record its details.</p>`);return;}
 const g=a.governance.find(g=>g.site===state.site),covers=scoped(a.cover);
 modal('Governance & cover',`${assuranceNotice}${g?`<dl class="detail-grid"><div><dt>Superintendent</dt><dd>${esc(g.superintendent)} · ${esc(g.superintendentReg)}</dd></div><div><dt>Supervising pharmacist</dt><dd>${esc(g.supervising)} · ${esc(g.supervisingReg)}</dd></div><div><dt>Premises registration / renewal</dt><dd>${esc(g.premises)} · ${esc(g.renewal)}</dd></div><div><dt>Evidence checked</dt><dd>${esc(g.evidence)}</dd></div></dl>${badge(governanceStatus(g),'gray')}${g.history?.length?`<details class="section"><summary>Previous governance records (${g.history.length})</summary>${g.history.map(h=>`<p class="small section">${esc(h.recordedAt)} · ${esc(h.superintendent)} / ${esc(h.supervising)} · ${esc(h.evidence)} · ${esc(h.reason)}</p>`).join('')}</details>`:''}`:'<p class="empty">Named roles and registration evidence not recorded.</p>'}<div class="buttons section">${reviewer()?btn(g?'Amend governance':'Record governance','assure:governance-form',''):''}${btn('Record cover / handover','assure:cover','secondary')}</div><h3 class="section">Cover history</h3>${covers.map(c=>`<div class="row"><div class="row-content"><h3>${esc(c.date)} · ${esc(c.name)}</h3><p>${esc(c.start)}–${esc(c.end)} · ${esc(c.kind)} · ${esc(c.registration)}<br>${esc(c.handover)}</p></div>${badge(c.outcome,c.outcome==='Gap / concern'?'red':'gray')}</div>`).join('')||'<p class="small muted section">No cover records yet.</p>'}<p class="field-note section"><a href="${ASSURANCE_SOURCES.governance}" target="_blank" rel="noopener">PSI governance requirements</a></p>`);
}
function governanceForm(){if(!requireReviewer())return;const g=assuranceState().governance.find(g=>g.site===state.site)||{};
 modal('Record named responsibilities',`<form id="assure-governance" data-site="${esc(state.site)}">${assuranceNotice}${assureField('superintendent','Superintendent pharmacist','text',g.superintendent)}${assureField('superintendentReg','PSI registration reference','text',g.superintendentReg)}${assureField('supervising','Supervising pharmacist','text',g.supervising)}${assureField('supervisingReg','PSI registration reference','text',g.supervisingReg)}${assureField('premises','Premises registration reference','text',g.premises)}${assureField('renewal','Registration renewal due','date',g.renewal)}${assureField('checkedBy','Evidence checked by')}${assureField('evidence','Appointment, experience and registration evidence reference','text',g.evidence)}<label class="checkbox"><input type="checkbox" required>I checked the appointment and applicable experience requirements against the source evidence.</label>${assureField('reason','Reason for recording / amendment')}${formFooter('Save governance record')}</form>`);
}
function coverForm(){if(!requireReviewer())return;
 modal('Pharmacist cover & handover',`<form id="assure-cover" data-site="${esc(state.site)}">${assuranceNotice}${assureField('date','Cover date','date',DEMO_DATE)}<div class="grid two"><div>${assureField('start','From','time')}</div><div>${assureField('end','Until','time')}</div></div>${assureField('name','Pharmacist / authorised cover name')}${assureField('registration','Registration evidence reference')}${assureSelect('kind','Cover arrangement',['Regular pharmacist','Locum pharmacist','Authorised temporary-absence arrangement'])}${assureSelect('outcome','Cover outcome',['Cover confirmed','Gap / concern'])}${assureNote('handover','Handover, checks and any gap details')}${assureField('checkedBy','Checked by')}${formFooter('Record cover')}</form>`);
}
function reviewChooser(){if(!requireReviewer())return;modal('What are you reviewing?',`<div class="assurance-choices">${REVIEW_PACKS.map(p=>row(esc(p.title),p.items.length+' evidence questions','audit','assure-review:'+p.id)).join('')}</div><p class="field-note section">These are operational review prompts, not a complete PSI assessment or certification.</p>`);}
function reviewForm(id){if(!requireReviewer())return;const p=REVIEW_PACKS.find(x=>x.id===id);if(!p)return;
 modal(p.title,`<form id="assure-review" data-pack="${p.id}" data-site="${esc(state.site)}">${assuranceNotice}<p class="field-note section"><a href="${ASSURANCE_SOURCES[p.source]}" target="_blank" rel="noopener">Check the current official guidance</a></p>${assureField('date','Review date','date',DEMO_DATE)}${assureField('reviewer','Reviewer name')}${p.id==='services'?assureSelect('service','Service',['Vaccination','Emergency contraception','Common Conditions Service','Prescription extension','Other approved service']):''}${p.id==='pcrs'?assureSelect('scheme','Scheme / scope',['GMS','DPS','LTI','High-tech','Multiple schemes']):''}${assureField('protocol','Approved local procedure / version or review scope')}${p.items.map((x,i)=>`<fieldset class="assurance-question"><legend>${esc(x)}</legend>${assureSelect('outcome'+i,'Outcome',['Evidence checked','Gap identified','Not applicable'])}${assureField('evidence'+i,'Evidence reference or reason for N/A')}</fieldset>`).join('')}${assureNote('note','Summary and immediate steps')}${assureField('next','Next review due','date','2026-11-05')}${assureField('owner','Follow-up owner')}${assureField('due','Follow-up due date','date','2026-10-12')}${formFooter('Save review')}</form>`,'Evidence review');
}
function reviewList(){const list=scoped(assuranceState().reviews);modal('Evidence reviews',`${list.map(r=>row(esc(r.title),siteName(r.site)+' · '+r.date+' · '+asStatus(r),'audit','assure-record:'+r.id)).join('')||'<p class="empty">No evidence reviews recorded.</p>'}${reviewer()?`<div class="buttons section">${btn('Start a review','assure:review','')}</div>`:''}`);}
function reviewDetail(id){const r=scoped(assuranceState().reviews).find(x=>x.id===id);if(!r)return;modal(esc(r.title),`<p class="small muted">${siteName(r.site)} · ${esc(r.date)} · ${esc(r.reviewer)}<br>${esc(r.protocol)} · ${esc(r.service||r.scheme||'')}</p>${badge(asStatus(r),'gray')}${r.answers.map(x=>`<div class="row"><div class="row-content"><h3>${esc(x.question)}</h3><p>${esc(x.outcome)} · ${esc(x.evidence)}</p></div></div>`).join('')}<p class="small section">${esc(r.note)}</p><p class="field-note">Next review: ${esc(r.next)} · Saved ${esc(r.recordedAt)}</p><div class="buttons section">${btn('View follow-up actions','close-nav:actions','secondary')}</div>`);}
function exceptionPanel(){return `<section class="section card"><h2>Operational exceptions</h2><p class="small muted section">Capture a discrepancy or concern and give pharmacist follow-up a clear owner.</p><div class="buttons section">${btn('Record an exception','assure:exception','secondary')}${btn('View exceptions','assure:exceptions','secondary')}</div></section>`;}
function exceptionForm(){if(!requireSite())return;modal('Record an exception',`<form id="assure-exception" data-site="${esc(state.site)}">${assuranceNotice}${assureSelect('type','Exception type',EXCEPTIONS)}${assureField('date','Identified on','date',DEMO_DATE)}${assureField('reference','Source-system / batch / record reference')}${assureNote('note','Concern and immediate steps taken')}${assureField('reportedBy','Reported by')}${assureField('owner','Follow-up pharmacist / responsible owner')}${assureField('due','Follow-up due','date',DEMO_DATE)}<p class="field-note">Notify the responsible person directly for urgent issues. This demo does not send alerts.</p>${formFooter('Save and create action')}</form>`);}
function exceptionList(){modal('Operational exceptions',`${scoped(assuranceState().exceptions).map(x=>`<div class="row"><div class="row-content"><h3>${esc(x.type)} · ${esc(x.reference)}</h3><p>${siteName(x.site)} · ${esc(x.date)} · ${esc(x.reportedBy)}<br>${esc(x.note)}</p></div>${btn('Action','action:'+x.action,'secondary sm')}</div>`).join('')||'<p class="empty">No operational exceptions recorded.</p>'}`);}
function competencePanel(){const list=scoped(assuranceState().competence);return `<section class="section card"><h2>Staff & service competence</h2><p class="small muted section">Record named training, assessment and renewal evidence. Completing a refresher alone does not establish service competence.</p><div class="buttons section">${reviewer()?btn('Record competence','assure:competence','secondary'):''}${btn('View training matrix','assure:matrix','secondary')}</div><p class="field-note section">${list.length} evidence records · ${list.filter(x=>x.next<DEMO_DATE||x.outcome==='Further assessment needed').length} need review.</p></section>`;}
function competenceForm(){if(!requireReviewer())return;modal('Record competence evidence',`<form id="assure-competence" data-site="${esc(state.site)}">${assuranceNotice}${assureField('name','Colleague name')}${assureSelect('role','Role',['Pharmacist','Locum pharmacist','Technician','Pharmacy assistant','Pharmacy manager'])}${assureSelect('topic','Training / competence area',COMPETENCIES)}${assureSelect('outcome','Assessment outcome',['Evidence reviewed','Further assessment needed','Not applicable'])}${assureField('date','Assessed on','date',DEMO_DATE)}${assureField('next','Review / renewal due','date','2027-10-05')}${assureField('assessor','Assessed by')}${assureField('evidence','Certificate, induction or assessment reference')}${assureNote('note','Scope, limitations and next steps')}${formFooter('Save evidence')}</form>`);}
function competenceMatrix(){const list=scoped(assuranceState().competence),names=[...new Set(list.map(r=>JSON.stringify([r.site,r.name])))];modal('Training evidence matrix',`${names.length?'<p class="field-note">Latest assessment per colleague and topic. Missing evidence is shown explicitly.</p>':''}${names.map(key=>{const [site,name]=JSON.parse(key);return `<section class="section"><h3>${esc(name)} · ${siteName(site)}</h3>${COMPETENCIES.map(topic=>{const r=list.filter(r=>r.site===site&&r.name===name&&r.topic===topic).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))[0];return `<div class="row"><div class="row-content"><h3>${esc(topic)}</h3><p>${r?esc(r.evidence)+' · '+esc(r.assessor)+' · review '+esc(r.next)+'<br>'+esc(r.note):'No evidence recorded'}</p></div>${badge(!r?'Not recorded':r.next<DEMO_DATE?'Review overdue':r.outcome,!r?'gray':r.next<DEMO_DATE||r.outcome==='Further assessment needed'?'amber':'gray')}</div>`;}).join('')}</section>`;}).join('')||'<p class="empty">No named competence evidence yet.</p>'}`);}
function assuranceSummary(){const a=assuranceState();return `<section class="section card"><h2>Assurance across pharmacies</h2><div class="assurance-list section">${activeSites().map(s=>{const g=a.governance.find(g=>g.site===s.id),rs=a.reviews.filter(r=>r.site===s.id),cs=a.competence.filter(r=>r.site===s.id);return `<div class="row"><div class="row-content"><h3>${s.name}</h3><p>Governance: ${governanceStatus(g)} · ${rs.length} reviews · ${cs.length} competence records</p></div>${badge(!g?'Evidence missing':g.renewal<DEMO_DATE?'Renewal overdue':!rs.length?'No reviews recorded':rs.some(r=>asStatus(r)!=='Recorded')?'Follow-up needed':'View evidence','gray')}</div>`;}).join('')}</div><div class="buttons section">${btn('Open assurance','nav:inspections','secondary')}</div></section>`;}
function assuranceEvidence(){const a=assuranceState();return `<section class="section"><h3>Branch assurance evidence</h3>${scoped(a.governance).map(g=>`<p class="small">${siteName(g.site)} · ${esc(g.superintendent)} / ${esc(g.supervising)} · premises ${esc(g.premises)} · renewal ${esc(g.renewal)} · ${esc(g.evidence)}</p>`).join('')||'<p class="small">Governance evidence not recorded.</p>'}${scoped(a.cover).map(c=>`<p class="small">Cover: ${siteName(c.site)} · ${esc(c.date)} ${esc(c.start)}–${esc(c.end)} · ${esc(c.name)} · ${esc(c.outcome)} · ${esc(c.handover)}</p>`).join('')}${scoped(a.reviews).map(r=>`<h3 class="section">${esc(r.title)} · ${siteName(r.site)}</h3><p class="small">${esc(r.date)} · ${esc(r.reviewer)} · ${esc(r.protocol)} · next ${esc(r.next)} · ${asStatus(r)}</p>${r.answers.map(x=>`<p class="small">${esc(x.question)} — ${esc(x.outcome)}: ${esc(x.evidence)}</p>`).join('')}`).join('')}${scoped(a.competence).map(c=>`<p class="small">Training: ${esc(c.name)} · ${esc(c.topic)} · ${esc(c.outcome)} · ${esc(c.evidence)} · next ${esc(c.next)}</p>`).join('')}${scoped(a.exceptions).map(x=>`<p class="small">Exception: ${x.id} · ${esc(x.type)} · ${esc(x.reference)} · action ${esc(x.action)}</p>`).join('')}</section>`;}
function assuranceAct(action){const [type,id]=action.split(':');if(type==='assure-review'){reviewForm(id);return true;}if(type==='assure-record'){reviewDetail(id);return true;}if(type!=='assure')return false;({governance:governanceDialog,'governance-form':governanceForm,cover:coverForm,review:reviewChooser,reviews:reviewList,exception:exceptionForm,exceptions:exceptionList,competence:competenceForm,matrix:competenceMatrix}[id]||(()=>{}))();return true;}
document.addEventListener('submit',e=>{
 const f=e.target;if(!f.id.startsWith('assure-'))return;e.preventDefault();if(!f.reportValidity())return;
 if(f.dataset.site!==state.site||!requireSite())return;
 if(f.id!=='assure-exception'&&!reviewer()){toast('An authorised demo reviewer is required.');return;}
 const v=Object.fromEntries(new FormData(f)),a=assuranceState(),base={id:'AS-'+crypto.randomUUID(),site:state.site,recordedAt:new Date().toISOString(),by:'Demo '+state.role};
 if(Object.values(v).some(x=>typeof x==='string'&&!x.trim())){toast('Complete the evidence fields.');return;}
 if(v.next&&v.next<v.date){toast('Review due date cannot be before the assessment.');return;}
 if(f.id==='assure-governance'){const old=a.governance.find(x=>x.site===state.site);a.governance=a.governance.filter(x=>x.site!==state.site);a.governance.push({...base,...v,history:old?[...(old.history||[]),{...old,history:undefined}]:[]});}
 else if(f.id==='assure-cover'){if(v.end<=v.start){toast('End time must be after start time. Split overnight cover into dated records.');return;}a.cover.push({...base,...v});if(v.outcome==='Gap / concern')addAction({site:state.site,title:'Review pharmacist cover gap: '+v.date,owner:v.checkedBy,due:v.date,source:base.id});}
 else if(f.id==='assure-review'){const p=REVIEW_PACKS.find(x=>x.id===f.dataset.pack);if(!p)return;const answers=p.items.map((question,i)=>({question,outcome:v['outcome'+i],evidence:v['evidence'+i]}));a.reviews.push({...base,title:p.title,pack:p.id,date:v.date,reviewer:v.reviewer,protocol:v.protocol,service:v.service,scheme:v.scheme,next:v.next,note:v.note,answers});answers.filter(x=>x.outcome==='Gap identified').forEach(x=>addAction({site:state.site,title:p.title+': '+x.question,owner:v.owner,due:v.due,source:base.id}));}
 else if(f.id==='assure-exception'){const action=addAction({site:state.site,title:v.type+': '+v.reference,owner:v.owner,due:v.due,source:base.id});a.exceptions.push({...base,...v,action:action.id});}
 else if(f.id==='assure-competence'){a.competence.push({...base,...v});if(v.outcome==='Further assessment needed')addAction({site:state.site,title:'Competence follow-up: '+v.name+' / '+v.topic,owner:v.assessor,due:v.next,source:base.id});}
 else return;
 save('Assurance evidence saved: '+f.id.replace('assure-',''));closeModal();render();toast('Evidence saved in this demo.');
});

render();
