/* PharmaTap demo data. No real operational or patient records. */
const DEMO_DATE='2026-10-05';
const SOURCES={
 locations:'https://www.stackspharmacy.ie/locations',
 errors:'https://www.psi.ie/practice-supports/practice-updates-and-learnings/advice-medication-error-management',
 sops:'https://www.psi.ie/practice-supports/practice-updates-and-learnings/advice-standard-operating-procedures-sops',
 storage:'https://www.psi.ie/practice-supports/guidance-and-guidelines-pharmacists-and-pharmacies/guidelines-storage-medicinal',
 equipment:'https://www.psi.ie/practice-supports/guidance-and-guidelines-pharmacists-and-pharmacies/guidelines-equipment',
 recalls:'https://www.hpra.ie/regulation/human-medicine/marketing-authorisation-holders/post-licensing/market-compliance-and-surveillance-of-medicines/quality-defects-and-recalls-of-medicines',
 assessment:'https://www.psi.ie/sites/default/files/2024-06/Pharmacy_Assessment_System_Guide.pdf'
};
const SITES=[
 ['skerries','Skerries','Dublin',7],['bettystown','Bettystown','Meath',1],['callan','Callan','Kilkenny',2],['tullow','Tullow','Carlow',9],['ratoath','Ratoath','Meath',10],['marley','Marley Park','Dublin',11],['lusk','Lusk','Dublin',12],['moyross','Moyross','Limerick',13],['laytown','Laytown','Meath',14],['clongriffin','Clongriffin','Dublin',22],['gorey','Gorey','Wexford',23],['glasnevin','Glasnevin','Dublin',24],['kilbarrack','Kilbarrack','Dublin',25],['darndale','Darndale','Dublin',26],['passage','Passage West','Cork',60],['ballymount','Ballymount','Dublin',74],
 ...[17,18,19,20].map(n=>['pending'+n,'Pharmacy '+n,'Awaiting confirmation',null])
].map(([id,name,county,webId])=>({id,name,county,source:webId?'https://www.stackspharmacy.ie/locations/'+webId:null,pending:!webId}));
const SOP_DEFS=[
 ['SOP-001','Reporting a medication error','Patient safety','Record, escalate and learn from a medication error.','errors',['Tell the pharmacist on duty promptly; immediate patient care takes priority over completing this form.','Record what happened, when it was discovered, the dispensing stage and whether the error reached the patient.','The pharmacist records their assessment, relevant contacts and corrective actions.','Assign preventive actions, share suitable anonymised learning and review whether the actions were effective.']],
 ['SOP-002','Recording a near miss','Patient safety','Capture errors intercepted before they reach the patient.','errors',['Make the situation safe and notify the pharmacist on duty.','Record the error type, stage of interception and contributing factors without unnecessary patient identifiers.','The reviewing pharmacist checks the record and identifies any preventive action.','Review patterns regularly and share learning with the pharmacy team.']],
 ['SOP-003','Medicine fridge temperature checks','Storage & stock','Record and review current, minimum and maximum refrigerator temperatures.','storage',['Use the designated monitoring device and record current, minimum and maximum readings at the agreed time.','Review the readings against the approved limits for the medicines stored.','If any reading is outside the agreed range, contact the pharmacist immediately and follow the approved excursion procedure.','Record the action taken and reset the minimum/maximum device only in accordance with its instructions.']],
 ['SOP-004','Temperature excursions','Storage & stock','Escalate and document a storage condition outside approved limits.','storage',['Notify the pharmacist on duty and record the readings, detection time and known duration.','Identify potentially affected stock and follow the pharmacist’s directions on segregation and assessment.','The pharmacist obtains the information needed to assess affected medicines; the app does not authorise release of stock.','Document the decision, supporting evidence, equipment investigation and any preventive actions.']],
 ['SOP-005','Room temperature monitoring','Storage & stock','Monitor the areas used to store medicinal products.','storage',['Record current, minimum and maximum readings for the designated storage area.','Check against the approved storage conditions and escalate any exception to the pharmacist.','Record the action taken and retain evidence of regular pharmacist review.']],
 ['SOP-006','Medicine recalls and quarantine','Storage & stock','Document each pharmacy’s response to a medicine recall.','recalls',['Read the actual recall notice and follow its product, batch and distribution scope.','Identify relevant stock, segregate affected packs and record the quantity and location.','Follow the recall instructions for returns and any onward communications.','The pharmacist reviews the evidence and confirms the site response.']],
 ['SOP-007','Expiry checks and stock rotation','Storage & stock','Identify and manage stock approaching or beyond expiry.','storage',['Check the designated stock area using the pharmacy’s approved expiry schedule.','Record the affected stock and escalate items requiring removal or assessment.','Apply the approved segregation, return or disposal process and record the outcome.']],
 ['SOP-008','Receiving medicinal products','Storage & stock','Check incoming deliveries against approved supply and storage arrangements.','storage',['Check the delivery, documentation and packaging against the order.','Identify items requiring special storage and follow the approved receiving procedure.','Record discrepancies and notify the pharmacist before accepting uncertain stock for supply.']],
 ['SOP-009','Equipment faults and maintenance','Premises & equipment','Report faults and retain evidence of service and repair.','equipment',['Identify the asset and record the fault, time and operational impact.','Notify the responsible person and follow the approved approach to taking unsafe equipment out of use.','Assign the repair, retain contractor evidence and record any checks before returning the asset to service.']],
 ['SOP-010','Thermometer calibration','Premises & equipment','Track calibration dates and supporting evidence.','storage',['Check the device identifier, calibration schedule and latest certificate.','Arrange calibration in accordance with the manufacturer’s recommendations and approved pharmacy procedure.','Retain the results and escalate any device found to be outside the permitted tolerance.']],
 ['SOP-011','Opening the pharmacy','Daily operations','Confirm the pharmacy is ready to operate safely.','assessment',['Confirm the responsible pharmacist arrangements using the local procedure.','Complete the assigned premises, equipment and storage checks.','Review handover items and unresolved safety issues before starting the day.']],
 ['SOP-012','Closing the pharmacy','Daily operations','Complete the day’s checks and secure the premises.','assessment',['Confirm outstanding patient safety issues have been handed over to the appropriate pharmacist.','Check required records and unresolved actions.','Follow the approved premises, stock and security closing procedure.']],
 ['SOP-013','Cleaning and hygiene','Daily operations','Record completion and exceptions to the local cleaning schedule.','assessment',['Use the approved cleaning schedule and materials for the relevant area.','Record completion and any areas that could not be cleaned.','Escalate defects or contamination concerns to the responsible person.']],
 ['SOP-014','Patient complaints','Patient safety','Document complaints and follow through on improvement actions.','assessment',['Listen to the concern and identify any immediate patient safety issue for the pharmacist.','Record the complaint using the approved privacy and complaints procedure.','Assign review, record the response and track improvement actions to completion.']],
 ['SOP-015','SOP review and approval','Governance','Keep procedures current, applicable and version controlled.','sops',['Assign a document owner and identify the scope and staff roles affected.','Review the procedure with the relevant staff and pharmacist governance roles.','Obtain authorised approval, record the effective date and archive the superseded version.','Communicate changes and record staff training and acknowledgement.']],
 ['SOP-016','Staff and locum induction','People & learning','Ensure staff know the local procedures relevant to their work.','sops',['Confirm role, supervision arrangements and access permissions.','Assign relevant current SOPs and local induction tasks.','Record training, questions and any competence assessment required by the pharmacist.']],
 ['SOP-017','Preventive actions and effectiveness','Governance','Follow improvement actions through to an evidence-based review.','errors',['Link the action to the incident, audit or concern.','Record an owner, due date and expected outcome.','Retain completion evidence and have the appropriate reviewer assess effectiveness.','Reopen or revise the action if the underlying issue persists.']],
 ['SOP-018','Internal pharmacy review','Governance','Review practice and maintain a documented improvement plan.','assessment',['Agree the scope and responsible reviewer.','Compare actual practice and records with the applicable approved procedures and guidance.','Record findings, assign actions and obtain the relevant pharmacist review.']],
 ['SOP-019','Controlled drug governance','Dispensing & services','Provide a review checklist linked to the pharmacy’s approved controlled drug procedures.','assessment',['Use the approved controlled drug procedures and applicable statutory records.','Record that the assigned governance review was completed without duplicating patient details in this app.','Escalate discrepancies directly to the pharmacist and record the related action reference.']],
 ['SOP-020','Prescription assessment and referral','Dispensing & services','Link staff to the pharmacist-led assessment and referral procedure.','sops',['Refer prescription queries to the pharmacist using the approved local process.','Document operational exceptions in the appropriate system.','Use authorised clinical references and the pharmacist’s professional judgement for clinical decisions.']],
 ['SOP-021','Monitored dosage system handover','Dispensing & services','Track operational exceptions and handover evidence for pack preparation.','assessment',['Follow the approved pack preparation, checking and handover procedure.','Record operational discrepancies and escalate them to the pharmacist.','Keep patient and prescription records in the designated clinical or dispensing system.']],
 ['SOP-022','Care home service handover','Dispensing & services','Track service issues between the pharmacy and care home team.','assessment',['Use the approved communications and delivery arrangements.','Record the service issue and promptly escalate any medicine or patient safety concern.','Track the assigned response and retain appropriately restricted evidence.']],
 ['SOP-023','Vaccination service readiness','Dispensing & services','Provide an operational readiness check linked to the approved service protocol.','sops',['Confirm that the authorised pharmacist has reviewed the current service protocol.','Complete the assigned equipment, storage and readiness checks.','Use the designated clinical record system for consent, assessment and administration records.']],
 ['SOP-024','Privacy and secure records','Governance','Limit information to what is necessary and keep access appropriate.','sops',['Use the designated record system and avoid unnecessary identifiers in general reports.','Apply the approved access, retention and information sharing procedure.','Escalate suspected privacy incidents to the designated responsible person.']]
];
const SOP_LIBRARY=SOP_DEFS.map(([id,title,category,objective,sourceKey,steps])=>({id,title,category,objective,source:SOURCES[sourceKey],steps,version:'1.0',status:'Demo current',owner:'Demo superintendent pharmacist',effective:'2026-10-01',review:'2027-10-01',scope:'All confirmed pharmacies',history:[]}));
const CHECK_TEMPLATES=[
 {id:'fridge',title:'Medicine fridge',subtitle:'Current, minimum and maximum temperatures',type:'temperature',icon:'temperature',sop:'SOP-003',time:'09:00'},
 {id:'room',title:'Dispensary room',subtitle:'Current, minimum and maximum temperatures',type:'room',icon:'temperature',sop:'SOP-005',time:'09:00'},
 {id:'opening',title:'Opening checks',subtitle:'Premises, equipment and handover',type:'list',icon:'sun',sop:'SOP-011',time:'09:00',items:['Pharmacist arrangements confirmed','Premises and equipment checked','Outstanding handover items reviewed']},
 {id:'cleaning',title:'Cleaning schedule',subtitle:'Dispensary surfaces and consultation room',type:'list',icon:'spark',sop:'SOP-013',time:'13:00',items:['Dispensary surfaces cleaned','Consultation room cleaned','Any exceptions reported']},
 {id:'closing',title:'Closing checks',subtitle:'Handover, records and security',type:'list',icon:'moon',sop:'SOP-012',time:'18:00',items:['Safety issues handed over','Records and actions reviewed','Premises secured according to local procedure']}
];
function seedState(){
 const reports=[
 {id:'PT-1001',site:'skerries',type:'Near miss',category:'Wrong strength',stage:'Final check',title:'Different strength selected during picking',description:'Demonstration record: a different strength was selected from the shelf and intercepted at the final check. No medicine reached a patient.',patient:'No',immediate:'Selection corrected and pharmacist on duty informed.',severity:'No harm identified',status:'Awaiting review',date:'2026-10-05',owner:'Demo pharmacist',actions:['A-1001'],timeline:[{text:'Report submitted by demo technician',time:'2026-10-05 09:18'}]},
 {id:'PT-1002',site:'marley',type:'Medication error',category:'Labelling',stage:'Supply',title:'Labelling discrepancy reported after supply',description:'Fictional demonstration case for pharmacist review. The clinical response and contacts are kept in a restricted record in a production system.',patient:'Yes',immediate:'Pharmacist notified and immediate response recorded in the designated patient record.',severity:'Requires pharmacist assessment',status:'In review',date:'2026-10-04',owner:'Demo pharmacist',actions:['A-1002'],timeline:[{text:'Report submitted',time:'2026-10-04 14:10'},{text:'Pharmacist review started',time:'2026-10-04 14:15'}]},
 {id:'PT-1003',site:'gorey',type:'Near miss',category:'Wrong medicine',stage:'Final check',title:'Similar packaging caught at final check',description:'Fictional example: similar packaging contributed to a selection error intercepted before supply.',patient:'No',immediate:'Pharmacist informed. Correct selection confirmed.',severity:'No harm identified',status:'Closed',date:'2026-10-02',owner:'Demo pharmacist',actions:[],timeline:[{text:'Report submitted',time:'2026-10-02 10:21'},{text:'Shelf separation reviewed and anonymised learning shared',time:'2026-10-03 12:00'}]}
 ];
 const actions=[
 {id:'A-1001',site:'skerries',title:'Review shelf separation for similar strengths',owner:'Supervising pharmacist',due:'2026-10-06',source:'PT-1001',status:'Open',evidence:'',review:''},
 {id:'A-1002',site:'marley',title:'Review labelling workflow and brief the team',owner:'Supervising pharmacist',due:'2026-10-04',source:'PT-1002',status:'Open',evidence:'',review:''},
 {id:'A-1003',site:'skerries',title:'Confirm fridge service appointment',owner:'Pharmacy manager',due:'2026-10-05',source:'M-1001',status:'Open',evidence:'',review:''},
 {id:'A-1004',site:'lusk',title:'Upload thermometer calibration evidence',owner:'Pharmacy manager',due:'2026-10-07',source:'M-1002',status:'Open',evidence:'',review:''},
 {id:'A-1005',site:'bettystown',title:'Complete expiry review of consultation stock',owner:'Supervising pharmacist',due:'2026-10-06',source:'Internal review',status:'Open',evidence:'',review:''}
 ];
 const maintenance=[
 {id:'M-1001',site:'skerries',title:'Fridge door seal requires inspection',asset:'Pharmaceutical fridge · FR-01',priority:'Normal',status:'Assigned',description:'Fictional fault: door seal showing wear. Service appointment requested.',owner:'Pharmacy manager',date:'2026-10-04',evidence:''},
 {id:'M-1002',site:'lusk',title:'Thermometer calibration due',asset:'Room thermometer · TM-02',priority:'Normal',status:'Open',description:'Sample scheduled calibration task.',owner:'Pharmacy manager',date:'2026-10-05',evidence:''},
 {id:'M-1003',site:'passage',title:'Consultation room light repaired',asset:'Consultation room',priority:'Normal',status:'Completed',description:'Fictional repair completed and checked.',owner:'Pharmacy manager',date:'2026-10-03',evidence:'Sample completion note: light replaced and checked.'}
 ];
 const checks=[];
 SITES.filter(s=>!s.pending).forEach((s,i)=>{if(i!==0&&i%4!==0){checks.push({id:'CK-'+s.id+'-fridge',site:s.id,template:'fridge',date:DEMO_DATE,current:4.2,min:3.8,max:5.1,result:'Within demo limits',by:'Demo colleague'});checks.push({id:'CK-'+s.id+'-opening',site:s.id,template:'opening',date:DEMO_DATE,result:'Completed',by:'Demo colleague'});}});
 const recall={id:'RC-DEMO-01',title:'Sample batch recall exercise',product:'Demonstration product — no real medicine',batch:'DEMO-001',date:DEMO_DATE,instructions:'Exercise only. Demonstrate checking the specified batch, recording stock found, segregation and the pharmacist’s review. A real response must follow the actual recall letter.',responses:SITES.filter(s=>!s.pending).slice(1,12).map(s=>({site:s.id,quantity:0,status:'Confirmed',by:'Demo pharmacist'}))};
 return {schema:1,site:'skerries',role:'Pharmacist',reports,actions,maintenance,checks,sops:structuredClone(SOP_LIBRARY),acknowledgements:[],learning:[],recall,audits:[],activity:[{text:'Demonstration workspace created',time:new Date().toISOString(),site:'group',role:'Demo'}]};
}
