import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readdir,readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {transferDatabase,applyMigrations} from '../scripts/neon-transfer.mjs';
const names=(await readdir('netlify/database/migrations')).sort();
const migrations=await Promise.all(names.map(async name=>({name,sql:await readFile(`netlify/database/migrations/${name}/migration.sql`,'utf8')})));
const adapter=pg=>({query:async(sql,params)=>{if(!params&&(sql.includes('CREATE TABLE organisations')||sql.includes('ALTER TABLE organisations')||sql.includes('ALTER TABLE reports')||sql.includes('CREATE TABLE report_photos')||sql.includes('CREATE TABLE installation_authorisation')||sql.includes('CREATE TABLE database_control')))return {rows:await pg.exec(sql)};return pg.query(sql,params);}});
async function fixture(){const sourcePg=new PGlite(),targetPg=new PGlite(),source=adapter(sourcePg),target=adapter(targetPg);await applyMigrations(source,migrations);const user=randomUUID(),site='a0e2cc87-2fb0-4a72-9bb4-1f8f4eeb476e',report=randomUUID(),action=randomUUID();await source.query("INSERT INTO memberships(user_id,pharmacy_id,display_name,role,active) VALUES($1,$2,'Simon','superintendent',false)",[user,site]);await source.query("INSERT INTO organisation_memberships(user_id,organisation_id,role) SELECT $1,id,'admin' FROM organisations",[user]);await source.query("INSERT INTO installation_setup(key,configured_user_id) VALUES('initial-organisations',$1)",[user]);await source.query("INSERT INTO reports(id,pharmacy_id,type,title,detail,occurred_at,created_by,idempotency_key,request_hash) VALUES($1,$2,'Maintenance','Saved record','Original report detail retained.',now(),$3,$4,'hash')",[report,site,user,randomUUID()]);await source.query("INSERT INTO actions(id,pharmacy_id,report_id,owner_id,due_at) VALUES($1,$2,$3,$4,now()+interval '1 day')",[action,site,report,user]);await source.query("INSERT INTO audit_events(pharmacy_id,entity_id,actor_id,event,payload) VALUES($1,$2,$3,'report.created',$4)",[site,report,user,JSON.stringify({test:['value',1],message:'Original content'})]);await source.query("INSERT INTO report_photos(report_id,pharmacy_id,content_type,data,sha256) VALUES($1,$2,'image/jpeg',$3,'test-hash')",[report,site,Buffer.from([255,216,255,219,255,217])]);return {sourcePg,targetPg,source,target,user};}
test('Neon transfer preserves records, access revocations and audit identity; retries do not recopy',async()=>{const f=await fixture();try{
 const result=await transferDatabase(f.source,f.target,migrations);assert.equal(result.manifest.pharmacies.count,18);assert.equal(result.manifest.reports.count,1);assert.equal(result.manifest.report_photos.count,1);assert.equal(Buffer.from((await f.target.query('SELECT data FROM report_photos')).rows[0].data).toString('hex'),'ffd8ffdbffd9');assert.equal(result.manifest.audit_events.count,1);assert.equal((await f.source.query('SELECT writes_paused FROM database_control')).rows[0].writes_paused,true);assert.equal((await f.target.query('SELECT writes_paused FROM database_control')).rows[0].writes_paused,false);assert.equal((await f.target.query('SELECT active FROM memberships')).rows[0].active,false);
 const row=(await f.target.query('SELECT * FROM audit_events')).rows[0];await f.target.query("INSERT INTO audit_events(pharmacy_id,entity_id,actor_id,event,payload) VALUES($1,$2,$3,'test',$4)",[row.pharmacy_id,row.entity_id,row.actor_id,'{}']);assert.equal((await f.target.query('SELECT max(id)::int AS n FROM audit_events')).rows[0].n,2);
 assert.equal((await transferDatabase(undefined,f.target,migrations)).alreadyTransferred,true);assert.equal((await f.target.query('SELECT count(*)::int AS n FROM reports')).rows[0].n,1);await assert.rejects(f.target.query("UPDATE reports SET title='changed'"),/append only/);
 }finally{await f.sourcePg.close();await f.targetPg.close();}});
test('failed Neon transfer rolls back target and reopens source; nonempty targets are refused',async()=>{const f=await fixture();try{
 const broken={query:async(sql,params)=>{if(sql.startsWith('INSERT INTO actions'))throw new Error('simulated transfer failure');return f.target.query(sql,params);}};
 await assert.rejects(transferDatabase(f.source,broken,migrations),/simulated/);assert.equal((await f.source.query('SELECT writes_paused FROM database_control')).rows[0].writes_paused,false);assert.equal((await f.target.query("SELECT to_regclass('public.reports') AS n")).rows[0].n,null);
 await applyMigrations(f.target,migrations);await assert.rejects(transferDatabase(f.source,f.target,migrations),/new empty/);assert.equal((await f.source.query('SELECT writes_paused FROM database_control')).rows[0].writes_paused,false);
 }finally{await f.sourcePg.close();await f.targetPg.close();}});
