export type CheckDefinition={id:string;title:string;fullTitle:string;frequency:string;owner:string;basis:string;enabled:boolean;conditional:boolean;sites:string[]};
export const checkCatalogue:CheckDefinition[]=[
 {
  "id": "check-1",
  "title": "Fridge temperature",
  "fullTitle": "Fridge Temperature Log",
  "frequency": "Daily",
  "owner": "Staff",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-2",
  "title": "Room temperature",
  "fullTitle": "Dispensary Room Temperature Log",
  "frequency": "Daily",
  "owner": "Staff",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-3",
  "title": "Error log review",
  "fullTitle": "Near Miss and Dispensing Error Log",
  "frequency": "Daily",
  "owner": "Staff",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-4",
  "title": "Closing & security",
  "fullTitle": "Closing and Security Check",
  "frequency": "Daily",
  "owner": "Staff",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-5",
  "title": "Opening & presence",
  "fullTitle": "Opening and Pharmacist Presence Check",
  "frequency": "Daily",
  "owner": "Pharmacist",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-6",
  "title": "Duty register",
  "fullTitle": "Duty Register Sign-In",
  "frequency": "Daily",
  "owner": "Pharmacist",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-7",
  "title": "Controlled drugs",
  "fullTitle": "Controlled Drugs Register Entries and Safe Check",
  "frequency": "Daily",
  "owner": "Pharmacist",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-8",
  "title": "Prescription register",
  "fullTitle": "Daily Prescription Register Sign-Off",
  "frequency": "Daily",
  "owner": "Pharmacist",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-9",
  "title": "FMD alerts",
  "fullTitle": "Medicine Authentication (FMD) Alerts Check",
  "frequency": "Daily",
  "owner": "Pharmacist",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-10",
  "title": "Owings & collections",
  "fullTitle": "Owings and Uncollected Prescriptions Review",
  "frequency": "Weekly",
  "owner": "Staff",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-11",
  "title": "Waste medicines",
  "fullTitle": "Patient-Returned and Waste Medicines Check",
  "frequency": "Weekly",
  "owner": "Staff",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-12",
  "title": "Cleaning & hygiene",
  "fullTitle": "Dispensary Cleaning and Hygiene Check",
  "frequency": "Weekly",
  "owner": "Staff",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-13",
  "title": "Fire alarm & exits",
  "fullTitle": "Fire Alarm and Exit Routes Check",
  "frequency": "Weekly",
  "owner": "Staff",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-14",
  "title": "Drug running balance",
  "fullTitle": "Controlled Drugs Running Balance Check",
  "frequency": "Weekly",
  "owner": "Pharmacist",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-15",
  "title": "OST records",
  "fullTitle": "Opioid Substitution Treatment Records Check",
  "frequency": "Weekly",
  "owner": "Pharmacist",
  "basis": "Good practice",
  "enabled": false,
  "conditional": true,
  "sites": []
 },
 {
  "id": "check-16",
  "title": "Recalls & notices",
  "fullTitle": "Recalls and Safety Notices Review",
  "frequency": "Weekly",
  "owner": "Pharmacist",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-17",
  "title": "Duty register review",
  "fullTitle": "Duty Register Review and Sign-Off",
  "frequency": "Weekly",
  "owner": "Supervising pharmacist",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-18",
  "title": "Expiry & rotation",
  "fullTitle": "Expiry Date and Stock Rotation Check",
  "frequency": "Monthly",
  "owner": "Staff",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-19",
  "title": "PCRS claims",
  "fullTitle": "PCRS Claims Submission and Reconciliation",
  "frequency": "Monthly",
  "owner": "Staff",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-20",
  "title": "High-tech medicines",
  "fullTitle": "High-Tech Medicines Reconciliation",
  "frequency": "Monthly",
  "owner": "Staff",
  "basis": "Other body",
  "enabled": false,
  "conditional": true,
  "sites": []
 },
 {
  "id": "check-21",
  "title": "Emergency equipment",
  "fullTitle": "First Aid, Emergency Lighting and Extinguisher Check",
  "frequency": "Monthly",
  "owner": "Staff",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-22",
  "title": "Drug reconciliation",
  "fullTitle": "Full Controlled Drugs Stock Reconciliation",
  "frequency": "Monthly",
  "owner": "Pharmacist",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-23",
  "title": "Vaccination supplies",
  "fullTitle": "Anaphylaxis Kit and Vaccination Supplies Check",
  "frequency": "Monthly",
  "owner": "Pharmacist",
  "basis": "Good practice",
  "enabled": false,
  "conditional": true,
  "sites": []
 },
 {
  "id": "check-24",
  "title": "Error trends",
  "fullTitle": "Near Miss and Error Trend Review",
  "frequency": "Monthly",
  "owner": "Supervising pharmacist",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-25",
  "title": "Training records",
  "fullTitle": "Staff Training Records Check",
  "frequency": "Monthly",
  "owner": "Supervising pharmacist",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-26",
  "title": "Premises inspection",
  "fullTitle": "Premises and Consultation Area Inspection",
  "frequency": "Quarterly",
  "owner": "Staff",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-27",
  "title": "Equipment maintenance",
  "fullTitle": "Equipment Calibration and Maintenance Check",
  "frequency": "Quarterly",
  "owner": "Staff",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-28",
  "title": "Safety walk-through",
  "fullTitle": "Health and Safety Walk-Through",
  "frequency": "Quarterly",
  "owner": "Staff",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-29",
  "title": "SOP spot audit",
  "fullTitle": "SOP Compliance Spot Audit",
  "frequency": "Quarterly",
  "owner": "Supervising pharmacist",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-30",
  "title": "Drug destruction",
  "fullTitle": "Controlled Drugs Destruction Records Check",
  "frequency": "Quarterly",
  "owner": "Supervising pharmacist",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-31",
  "title": "Delivery service",
  "fullTitle": "Delivery Service Check (only if the pharmacy delivers)",
  "frequency": "Quarterly",
  "owner": "Supervising pharmacist",
  "basis": "PSI, local frequency",
  "enabled": false,
  "conditional": true,
  "sites": []
 },
 {
  "id": "check-32",
  "title": "Confidentiality",
  "fullTitle": "Confidentiality and Confidential Waste Check",
  "frequency": "Quarterly",
  "owner": "Supervising pharmacist",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-33",
  "title": "Controlled sales",
  "fullTitle": "Non-Prescription Controlled Sales Audit (codeine, pseudoephedrine)",
  "frequency": "Quarterly",
  "owner": "Supervising pharmacist",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-34",
  "title": "Complaints & incidents",
  "fullTitle": "Complaints and Incidents Review",
  "frequency": "Quarterly",
  "owner": "Supervising pharmacist",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-35",
  "title": "Data & access",
  "fullTitle": "Data Protection and System Access Review",
  "frequency": "Quarterly",
  "owner": "Owner / Superintendent",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-36",
  "title": "Fire drill",
  "fullTitle": "Fire Drill",
  "frequency": "Twice yearly",
  "owner": "Staff",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-37",
  "title": "PSI self-assessment",
  "fullTitle": "PSI Pharmacy Assessment System Self-Assessment",
  "frequency": "Annual",
  "owner": "Supervising pharmacist",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-38",
  "title": "Training & CPD",
  "fullTitle": "Staff Training Needs and CPD Review",
  "frequency": "Annual",
  "owner": "Supervising pharmacist",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-39",
  "title": "Clinical training",
  "fullTitle": "Vaccination and Clinical Service Training Renewal",
  "frequency": "Annual",
  "owner": "Supervising pharmacist",
  "basis": "Good practice",
  "enabled": false,
  "conditional": true,
  "sites": []
 },
 {
  "id": "check-40",
  "title": "PSI registration",
  "fullTitle": "PSI Pharmacy Registration Renewal",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-41",
  "title": "Action plan sign-off",
  "fullTitle": "Self-Assessment Action Plan Sign-Off",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "PSI",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-42",
  "title": "SOP annual review",
  "fullTitle": "SOP Full Review and Staff Sign-Off",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-43",
  "title": "Fridge servicing",
  "fullTitle": "Fridge and Thermometer Servicing",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "PSI, local frequency",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-44",
  "title": "Registration checks",
  "fullTitle": "Pharmacist and Staff Registration Verification",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-45",
  "title": "Business continuity",
  "fullTitle": "Business Continuity Plan Review",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-46",
  "title": "Contractor review",
  "fullTitle": "Contractor Review (waste, pest control, maintenance)",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "Good practice",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-47",
  "title": "Safety statement",
  "fullTitle": "Safety Statement and Risk Assessment Review",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-48",
  "title": "Fire servicing",
  "fullTitle": "Fire Equipment Servicing",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-49",
  "title": "Insurance renewal",
  "fullTitle": "Professional Indemnity and Insurance Renewal",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 },
 {
  "id": "check-50",
  "title": "Records disposal",
  "fullTitle": "Data Retention and Records Disposal Review",
  "frequency": "Annual",
  "owner": "Owner / Superintendent",
  "basis": "Other body",
  "enabled": true,
  "conditional": false,
  "sites": []
 }
];
