import {checkQuestions,type CheckQuestion} from './check-questions';
import {validateCheckAnswers,type CheckAnswer} from './check-answers';
import type {CheckDefinition} from './checks-catalogue';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Context={siteId:string;api:(path:string,options?:RequestInit)=>Promise<any>};
export function renderChecklistForm(host:Element,check:CheckDefinition,context:Context){
 const questions=checkQuestions[check.id];if(!questions)return;
 const row=(q:CheckQuestion,index:number)=>`<div class="check-record-row" data-question="${q.id}" data-row="${index}">${q.fields!.map(f=>`<label>${esc(f.label)}<input data-field="${f.id}" type="${f.type==='date'?'date':['number','count','nonnegative'].includes(f.type)?'number':'text'}" ${['number','nonnegative'].includes(f.type)?'step="any"':''} ${['count','nonnegative'].includes(f.type)?'min="0"':''} ${f.type==='count'?'step="1"':''} maxlength="2000" required></label>`).join('')}${q.repeat&&index>0?'<button type="button" class="secondary" data-remove-row>Remove</button>':''}</div>`;
 host.insertAdjacentHTML('beforeend',`<form id="check-complete"><p class="help">Answer each question. For any No, record the issue or action taken.</p>${questions.map((q,i)=>`<fieldset class="check-question" data-q="${q.id}"><legend><span>${i+1}.</span> ${esc(q.label)}</legend>${q.kind==='yesno'?`<div class="check-answer-options">${['Yes','No'].map(a=>`<label><input type="radio" name="${q.id}" value="${a}" required><span>${a}</span></label>`).join('')}</div><label class="check-issue" hidden>Issue or action taken<textarea name="note-${q.id}" maxlength="2000" rows="2"></textarea></label>`:`<div data-rows>${row(q,0)}</div>${q.repeat?`<button class="secondary" type="button" data-add-row="${q.id}">Add ${check.id==='check-1'?'fridge':'storage area'}</button>`:''}`}</fieldset>`).join('')}<p class="error" id="check-save-error" role="alert"></p><button id="check-submit">Complete checklist</button><p class="help">Saved with your name and completion time.</p></form><section id="check-records" class="check-records"><h3>Recent records</h3><p>Loading…</p></section>`);
 const form=host.querySelector<HTMLFormElement>('#check-complete')!;let retry:{key:string;payload:string}|undefined;
 form.addEventListener('change',()=>{form.querySelectorAll<HTMLElement>('[data-q]').forEach(fieldset=>{const no=fieldset.querySelector<HTMLInputElement>('input[value=No]')?.checked,issue=fieldset.querySelector<HTMLElement>('.check-issue');if(issue){issue.hidden=!no;const note=issue.querySelector('textarea')!;note.required=!!no;}});});
 form.addEventListener('click',e=>{const button=(e.target as Element).closest<HTMLElement>('button');if(button?.hasAttribute('data-remove-row'))button.closest('.check-record-row')!.remove();if(button?.dataset.addRow){const q=questions.find(q=>q.id===button.dataset.addRow)!;const rows=button.parentElement!.querySelector('[data-rows]')!;if(rows.children.length<50)rows.insertAdjacentHTML('beforeend',row(q,rows.children.length));}});
 form.addEventListener('submit',async e=>{
  e.preventDefault();const button=form.querySelector<HTMLButtonElement>('#check-submit')!,error=form.querySelector('#check-save-error')!;error.textContent='';
  const answers:Record<string,CheckAnswer>={},notes:Record<string,string>={};
  for(const q of questions){if(q.kind==='yesno'){answers[q.id]=(form.querySelector<HTMLInputElement>(`input[name="${q.id}"]:checked`)?.value||'');notes[q.id]=form.querySelector<HTMLTextAreaElement>(`[name="note-${q.id}"]`)!.value;}else answers[q.id]=Array.from(form.querySelectorAll<HTMLElement>(`[data-question="${q.id}"]`)).map(r=>Object.fromEntries(Array.from(r.querySelectorAll<HTMLInputElement>('input')).map(input=>[input.dataset.field!,input.value])));}
  try{validateCheckAnswers(check.id,answers,notes);}catch(e){error.textContent=(e as Error).message;return;}
  const payload=JSON.stringify({pharmacyId:context.siteId,checkId:check.id,answers,notes});if(!retry||retry.payload!==payload)retry={key:crypto.randomUUID(),payload};button.disabled=true;button.textContent='Saving…';
  try{await context.api('/checklists',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':retry.key},body:payload});form.innerHTML='<div role="status"><h3>Checklist saved</h3><p>Your answers and completion time have been recorded.</p><button type="button" class="secondary" id="check-another">Record another check</button></div>';form.querySelector('#check-another')!.addEventListener('click',()=>{host.querySelector('#check-complete')?.remove();host.querySelector('#check-records')?.remove();renderChecklistForm(host,check,context);});await load();}catch(e){error.textContent=(e as Error).message;button.disabled=false;button.textContent='Retry save';}
 });
 async function load(){const records=host.querySelector('#check-records')!;try{const result=await context.api('/checklists?pharmacyId='+encodeURIComponent(context.siteId));if(!host.contains(records))return;records.innerHTML='<h3>Recent records</h3>'+result.records.filter((r:any)=>r.check_id===check.id).slice(0,10).map((r:any)=>`<details class="check-saved"><summary>${esc(new Date(r.created_at).toLocaleString('en-IE'))} · ${esc(r.completed_by)} · ${r.failures?'Needs attention':'All Yes'}</summary>${r.questions.map((q:any)=>`<p><strong>${esc(q.label)}</strong><br>${Array.isArray(r.answers[q.id])?r.answers[q.id].map((row:any)=>q.fields.map((f:any)=>`${esc(f.label)}: ${esc(row[f.id])}`).join(' · ')).join('<br>'):esc(r.answers[q.id])}${r.notes[q.id]?'<br>'+esc(r.notes[q.id]):''}</p>`).join('')}</details>`).join('')||'<h3>Recent records</h3><p>No completions yet.</p>';}catch(e){if(host.contains(records))records.innerHTML='<p class="error">'+esc((e as Error).message)+'</p><button class="secondary" data-retry-records>Retry records</button>';records.querySelector('[data-retry-records]')?.addEventListener('click',()=>void load());}}
 void load();
}
