import {statusPanels} from './status-panels';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Context={organisationId:string;api:(path:string,options?:RequestInit)=>Promise<any>;updated:()=>Promise<void>};
export async function renderManage(host:Element,ctx:Context,initialView='sites'){
 host.innerHTML='<h1>Manage</h1><p role="status">Loading sites and users…</p>';
 try{
 const data=await ctx.api('/manage?organisationId='+encodeURIComponent(ctx.organisationId));if(!host.isConnected)return;
 const siteStatus=()=>statusPanels(data.sites.filter((s:any)=>s.has_admin&&s.has_reviewer).length,data.sites.filter((s:any)=>s.has_admin&&!s.has_reviewer).length,data.sites.filter((s:any)=>!s.has_admin).length);
 const users=[...new Map(data.users.map((u:any)=>[u.user_id,u])).values()] as any[];
 host.innerHTML=`<h1>Manage</h1><div class="report-switch" role="group" aria-label="Manage view"><button data-manage-view="sites" aria-pressed="true">Sites</button><button data-manage-view="users" aria-pressed="false">Users</button></div>${siteStatus()}<p class="help">Reviewer and admin assigned · Reviewer missing · Admin missing</p><section id="manage-sites"><div class="row"><h2>Sites</h2><button data-manage-add="site">Add site</button></div><div class="manage-list">${data.sites.map((s:any)=>`<article class="card"><strong>${esc(s.name)}</strong>${s.county?`<small>${esc(s.county)}</small>`:''}</article>`).join('')}</div></section><section id="manage-users" hidden><div class="row"><h2>Users</h2><button data-manage-add="user">Add user</button></div><div class="manage-list">${users.map(u=>`<article class="card"><strong>${esc(u.display_name)}</strong>${u.email?`<span>${esc(u.email)}</span>`:''}<small>${esc(({staff:'Staff',manager:'Pharmacist',superintendent:'Organisation admin'} as any)[u.role])} · ${data.users.filter((r:any)=>r.user_id===u.user_id).map((r:any)=>esc(r.site_name)).join(', ')}</small></article>`).join('')||'<p>No users yet.</p>'}</div></section><section id="manage-form"></section>`;
 let view='sites';
 host.querySelectorAll<HTMLElement>('[data-manage-view]').forEach(b=>b.onclick=()=>{view=b.dataset.manageView!;host.querySelectorAll<HTMLElement>('[data-manage-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));(host.querySelector('#manage-sites') as HTMLElement).hidden=view!=='sites';(host.querySelector('#manage-users') as HTMLElement).hidden=view!=='users';host.querySelector('.status-panels')!.outerHTML=view==='sites'?siteStatus():statusPanels(users.length,0,0);host.querySelector('.help')!.textContent=view==='sites'?'Reviewer and admin assigned · Reviewer missing · Admin missing':'Users with active site access';host.querySelector('#manage-form')!.innerHTML='';});
 host.querySelectorAll<HTMLElement>('[data-manage-add]').forEach(b=>b.onclick=()=>{
 const site=b.dataset.manageAdd==='site',target=host.querySelector('#manage-form')!;
 target.innerHTML=`<section class="card"><div class="row"><h2>Add ${site?'site':'user'}</h2><button class="secondary" data-manage-cancel>Cancel</button></div><form id="admin-create"><label>${site?'Site name':'Full name'}<input name="name" required maxlength="120"></label>${site?'<label>County (optional)<input name="county" maxlength="80"></label>':`<label>Email<input name="email" type="email" required maxlength="254"></label><label>Role<select name="role"><option value="staff">Staff</option><option value="manager">Pharmacist</option><option value="superintendent">Organisation admin</option></select></label><fieldset class="check-sites"><legend>Sites</legend>${data.sites.map((s:any)=>`<label><input name="siteIds" type="checkbox" value="${esc(s.id)}">${esc(s.name)}</label>`).join('')}</fieldset><p class="help">Organisation admins receive access to all sites. New users set their password using Reset password on the sign-in screen.</p>`}<p class="error" role="alert"></p><button>Add ${site?'site':'user'}</button></form></section>`;
 target.querySelector('[data-manage-cancel]')!.addEventListener('click',()=>target.innerHTML='');
 target.querySelector<HTMLInputElement>('input')!.focus();target.scrollIntoView({block:'start',behavior:'smooth'});
 const form=target.querySelector<HTMLFormElement>('form')!,id=crypto.randomUUID();
 if(!site)(form.elements.namedItem('role') as HTMLSelectElement).onchange=()=>{const all=(form.elements.namedItem('role') as HTMLSelectElement).value==='superintendent';form.querySelectorAll<HTMLInputElement>('[name=siteIds]').forEach(c=>{c.disabled=all;if(all)c.checked=true;});};
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button')!,error=form.querySelector('.error')!;const f=new FormData(form);const role=f.get('role');const selected=role==='superintendent'?data.sites.map((s:any)=>s.id):f.getAll('siteIds');if(!site&&!selected.length){error.textContent='Choose at least one site.';return;}button.disabled=true;error.textContent='';try{await ctx.api('/manage/'+(site?'sites':'users'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,organisationId:ctx.organisationId,name:f.get('name'),county:f.get('county'),email:f.get('email'),role,siteIds:selected})});await ctx.updated();if(host.isConnected){await renderManage(host,ctx,view);host.insertAdjacentHTML('afterbegin',`<p class="manage-success" role="status">${site?'Site added.':'User added. They can sign in, or use Reset password to set their password.'}</p>`);}}catch(e){error.textContent=(e as Error).message;}finally{button.disabled=false;}};
 });
 if(initialView==='users')host.querySelector<HTMLElement>('[data-manage-view=users]')?.click();
 }catch(e){if(host.isConnected){host.innerHTML='<h1>Manage</h1><section class="card"><p class="error" role="alert"></p><button>Retry</button></section>';host.querySelector('.error')!.textContent=(e as Error).message;host.querySelector('button')!.onclick=()=>void renderManage(host,ctx);}}
}
