import {sopCatalogue,sopGroups,type SopGroup} from './sops-catalogue';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let mode='sops',group:SopGroup='Medicines',selected='',scope='',drafts:any[]=[],loaded=false,loading=false,loadError='';
export function resetSops(){mode='sops';group='Medicines';selected='';drafts=[];loaded=false;loading=false;loadError='';scope='';}
export function sopsBack(){if(!selected)return false;selected='';return true;}
type Context={organisationId:string;siteId:string;role:string;api:(path:string,options?:RequestInit)=>Promise<any>};
const paths:Record<SopGroup,string>={Medicines:'M8 3a5 5 0 0 0-5 5v8a5 5 0 0 0 10 0V8a5 5 0 0 0-5-5z M3 12h10 M17 8h4 M17 12h4 M17 16h4',Dispensing:'M8 4H5v17h14V4h-3 M8 2h8v5H8z M8 11h8 M8 15h5','Non-prescription':'M3 7h18v14H3z M8 7V3h8v4 M12 11v6 M9 14h6',Governance:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6',Services:'M9 3h6v6h6v6h-6v6H9v-6H3V9h6z'};
export function renderSops(host:Element,context:Context){
 const next=context.organisationId+':'+context.siteId+':'+context.role;
 if(scope!==next){resetSops();scope=next;}
 const reviewer=['manager','superintendent'].includes(context.role),admin=context.role==='superintendent';
 const redraw=()=>renderSops(host,context),topic=sopCatalogue.find(s=>s.id===selected),draft=drafts.find(s=>s.id===selected);
 host.innerHTML=`<h1>SOPs</h1>${reviewer&&!selected?`<div class="report-switch sops-switch" role="group" aria-label="SOP view"><button data-sops-mode="sops" aria-pressed="${mode==='sops'}">SOPs</button><button data-sops-mode="dashboard" aria-pressed="${mode==='dashboard'}">Dashboard</button>${admin?`<button data-sops-mode="create" aria-pressed="${mode==='create'}">Create</button>`:''}</div>`:''}<section id="sops-body"></section>`;
 const body=host.querySelector('#sops-body')!;
 if(topic){body.innerHTML=`<section class="card training-detail"><div class="row"><h2>${esc(topic.name)}</h2><button class="secondary" data-sops-back>Back</button></div><div class="check-meta"><span class="pill">${esc(topic.group)}</span><span>Content not added</span></div><p>${topic.group==='Services'?'Required where this service is offered.':'Add a procedure that describes how this pharmacy carries out the task.'}</p><p class="help">No approved SOP is available for this topic yet.</p>${admin?'<button data-sops-from-topic>Create SOP</button>':''}</section>`;}
 else if(draft&&reviewer){body.innerHTML=`<section class="card training-detail"><div class="row"><h2>${esc(draft.title)}</h2><button class="secondary" data-sops-back>Back</button></div><div class="check-meta"><span class="pill">Draft</span><span>${esc(draft.category)} · Version ${esc(draft.version_label)}</span></div><p>Review date: ${esc(String(draft.review_date).slice(0,10))}</p>${draft.supplier?`<p>Supplier: ${esc(draft.supplier)}</p>`:''}${draft.has_pdf?`<a class="button" href="/api/workspace/sops/${encodeURIComponent(draft.id)}/pdf">Download PDF</a>`:`<div class="detail">${esc(draft.content)}</div>`}<p class="help">Awaiting review and approval. Staff cannot access this draft.</p></section>`;}
 else if(admin&&mode==='create'){
 body.innerHTML=`<section class="card sop-editor"><h2>Create SOP</h2><form id="sop-create"><label>Title<input name="title" required minlength="3" maxlength="160"></label><div class="columns"><label>Category<select name="category">${sopGroups.map(g=>`<option ${group===g?'selected':''}>${esc(g)}</option>`).join('')}</select></label><label>Version<input name="version" value="1.0" required maxlength="30"></label></div><label>Review date<input name="reviewDate" type="date" required></label><label>Source<select name="source"><option value="write">Write an SOP</option><option value="upload">Upload supplier SOP</option></select></label><div id="sop-written"><label>Procedure<textarea name="content" rows="9" maxlength="30000" required placeholder="Describe how the task is carried out at this pharmacy."></textarea></label></div><div id="sop-uploaded" hidden><label>Supplier<input name="supplier" maxlength="160" disabled></label><label>PDF file<input name="file" type="file" accept="application/pdf,.pdf" disabled></label><p class="help">PDF, up to 2 MB.</p></div><p class="help">Saved as a draft for this site. Review and approval are required before staff use.</p><p class="error" id="sop-error" role="alert"></p><button>Save draft</button></form></section>`;
 const form=body.querySelector<HTMLFormElement>('#sop-create')!,source=form.elements.namedItem('source') as HTMLSelectElement;
 source.onchange=()=>{const upload=source.value==='upload';(body.querySelector('#sop-written') as HTMLElement).hidden=upload;(body.querySelector('#sop-uploaded') as HTMLElement).hidden=!upload;for(const name of ['supplier','file']){const field=form.elements.namedItem(name) as HTMLInputElement;field.disabled=!upload;field.required=upload;}const field=form.elements.namedItem('content') as HTMLTextAreaElement;field.disabled=upload;field.required=!upload;};
 const id=crypto.randomUUID();form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button')!,error=body.querySelector('#sop-error')!;button.disabled=true;button.textContent='Saving…';error.textContent='';try{
 const f=new FormData(form),payload:any={id,pharmacyId:context.siteId,title:f.get('title'),category:f.get('category'),version:f.get('version'),reviewDate:f.get('reviewDate'),supplier:f.get('supplier')||'',content:f.get('content')||''};
 if(source.value==='upload'){const file=f.get('file') as File;if(!file?.size||file.size>2097152)throw new Error('Choose a PDF smaller than 2 MB.');const bytes=new Uint8Array(await file.arrayBuffer());if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw new Error('Choose a valid PDF file.');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));payload.pdf=btoa(binary);}
 await context.api('/sops',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
 if(scope===next&&host.isConnected){selected='';mode='dashboard';loaded=false;loadError='';redraw();}
 }catch(e){error.textContent=(e as Error).message;}finally{button.disabled=false;button.textContent='Save draft';}};
 }else if(reviewer&&mode==='dashboard'){
 body.innerHTML=`<section class="summary checks-summary"><span><strong>${sopCatalogue.length}</strong>SOP topics</span><span><strong>${loaded?drafts.length:'—'}</strong>Drafts</span><span><strong>0</strong>Approved SOPs</span></section><section class="card"><h2>Drafts for review</h2>${loadError?`<p class="error">${esc(loadError)}</p><button class="secondary" data-sops-retry>Retry</button>`:!loaded?'<p>Loading drafts…</p>':!drafts.length?'<p>No drafts yet.</p>':drafts.map(d=>`<button class="sop-draft" data-sops-draft="${esc(d.id)}"><strong>${esc(d.title)}</strong><span>${esc(d.category)} · Version ${esc(d.version_label)} · Draft</span></button>`).join('')}<p class="help">Acknowledgement and review tracking will appear when the approval workflow is connected.</p></section>`;
 }else{
 body.innerHTML=`<div class="check-frequencies training-groups" role="group" aria-label="SOP category">${sopGroups.map(g=>`<button data-sops-group="${g}" aria-pressed="${group===g}">${esc(g)}</button>`).join('')}</div>${group==='Services'?'<p class="help">For services offered at your pharmacy.</p>':''}<section class="report-tiles training-tiles sop-tiles" aria-label="${esc(group)} SOPs">${sopCatalogue.filter(s=>s.group===group).map(s=>`<button class="report-tile training-tile" data-sops-open="${s.id}"><span class="report-tile-icon"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[s.group]}"/></svg></span><strong>${s.title.map(t=>`<span>${esc(t)}</span>`).join('')}</strong><span>${s.description.map(t=>`<span>${esc(t)}</span>`).join('')}</span></button>`).join('')}</section>`;
 }
 host.querySelectorAll<HTMLElement>('[data-sops-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.sopsMode!;redraw();});
 host.querySelectorAll<HTMLElement>('[data-sops-group]').forEach(b=>b.onclick=()=>{group=b.dataset.sopsGroup as SopGroup;redraw();});
 host.querySelectorAll<HTMLElement>('[data-sops-open],[data-sops-draft]').forEach(b=>b.onclick=()=>{selected=b.dataset.sopsOpen||b.dataset.sopsDraft!;redraw();window.scrollTo({top:0,behavior:'instant'});});
 host.querySelector('[data-sops-back]')?.addEventListener('click',()=>{selected='';redraw();});
 host.querySelector('[data-sops-retry]')?.addEventListener('click',()=>{loadError='';loaded=false;redraw();});
 host.querySelector('[data-sops-from-topic]')?.addEventListener('click',()=>{const title=topic!.name;group=topic!.group;selected='';mode='create';redraw();(host.querySelector('[name=title]') as HTMLInputElement).value=title;});
 if(reviewer&&mode==='dashboard'&&!loaded&&!loading&&!loadError){loading=true;void context.api('/sops?pharmacyId='+encodeURIComponent(context.siteId)).then(result=>{if(scope===next&&host.isConnected){drafts=result.drafts;loaded=true;loading=false;redraw();}}).catch(e=>{if(scope===next&&host.isConnected){loading=false;loadError=(e as Error).message;redraw();}});}
}
