export const trainingGroups=['Core','Pharmacy','Dispensary','Pharmacists','Risk-based'] as const;
export type TrainingGroup=typeof trainingGroups[number];
export type TrainingModule={id:string;title:[string,string];name:string;description:[string,string];group:TrainingGroup;audience:string;condition:string;topics:string[];evidence:string;source?:string};
const psi='https://www.psi.ie/practice-supports/guidance-and-guidelines-pharmacists-and-pharmacies/psi-guidance-pharmacy';
const vaccination='https://www.psi.ie/education-and-training/vaccinations-training';
const manual='https://www.hsa.ie/eng/topics/health_and_safety_myths/myth_4_manual_handling_training/';
const safety='https://www.hsa.ie/eng/topics/managing_health_and_safety/safety_statement_and_risk_assessment/';
const cpd='https://www.psi.ie/education-and-training/continuing-professional-development-cpd/eportfolio-review-process';
const rows:[string,[string,string],string,[string,string],TrainingGroup,string,string,string[],string,string?][]=[
 ['induction',['Safety','induction'],'Safety induction and Safety Statement',['Workplace safety','Stay safe at work'],'Core','All staff','On joining and when workplace risks or the Safety Statement change.',['Site hazards and controls','Safety Statement and staff responsibilities','Reporting hazards and getting help'],'Dated induction and Safety Statement acknowledgement.',safety],
 ['fire',['Fire','safety'],'Fire safety and emergency evacuation',['Prevent fires','Evacuate safely'],'Core','All staff','Use the site emergency plan and include practical drills.',['Alarm and evacuation procedures','Assembly point and emergency contacts','Site fire precautions and drills'],'Training record and participation in site drills.',safety],
 ['handling',['Manual','handling'],'Manual handling',['Move loads safely','Reduce injury risk'],'Core','Staff with handling risks','Assign where the role involves a manual-handling risk; training supports risk controls.',['Identify hazardous handling tasks','Use handling aids and safer work methods','Practise relevant tasks with a competent trainer'],'Risk-based instruction and practical training record.',manual],
 ['privacy',['Data','protection'],'Data protection and patient confidentiality',['Protect patient data','Keep it confidential'],'Core','All staff','Apply to the information and systems used in the role.',['Confidentiality and health information','Secure access and information sharing','Recognise and report a data breach'],'Dated training record and confidentiality acknowledgement.'],
 ['children',['Children','First'],'Children First awareness',['Recognise concerns','Safeguard children'],'Core','All staff','Awareness for all; statutory duties and mandated-person responsibilities depend on the role.',['Recognising safeguarding concerns','Local safeguarding and reporting arrangements','Role-specific responsibilities'],'Relevant awareness certificate and local safeguarding briefing.'],
 ['dignity',['Dignity','at work'],'Dignity at work',['Respect colleagues','Address bullying'],'Core','All staff','Expected good practice under relevant codes; follow the employer policy.',['Respectful workplace behaviour','Bullying and harassment','Raising concerns and support'],'Dated training record and policy acknowledgement.'],
 ['sops',['Role-based','SOPs'],'Standard operating procedures',['Read your SOPs','Know your role'],'Pharmacy','All staff','Assign only current SOPs relevant to the person’s duties.',['Locate current approved procedures','Understand role-specific responsibilities','Acknowledge updates and demonstrate competence'],'Signed, dated SOP training and version acknowledgement.',psi],
 ['otc',['OTC','medicines'],'Sale of non-prescription medicines',['Ask key questions','Refer safely'],'Pharmacy','Relevant pharmacy staff','Training must reflect the products supplied and pharmacist supervision.',['Structured questioning such as WWHAM','Referral to the pharmacist','Codeine and other restricted-product procedures'],'Observed competence and dated training record.',psi],
 ['supervision',['Pharmacist','supervision'],'Pharmacist supervision rules',['Know your limits','When to escalate'],'Pharmacy','All staff','Follow approved procedures for pharmacist cover and any authorised absence arrangements.',['Activities requiring pharmacist oversight','Limits of each staff role','Escalation when pharmacist cover changes'],'Role-specific briefing and SOP acknowledgement.',psi],
 ['incidents',['Errors &','complaints'],'Error, near-miss and complaints handling',['Report concerns','Learn from incidents'],'Pharmacy','All staff','Follow local reporting procedures and pharmacist review requirements.',['Recognise errors and near misses','Prompt reporting and patient-safety escalation','Complaints handling and shared learning'],'Dated training and role-specific competency evidence.',psi],
 ['dispensing',['Dispensing','procedures'],'Dispensing and accuracy-checking procedures',['Dispense safely','Know checking roles'],'Dispensary','Dispensary staff and technicians','Tasks and checking responsibilities require appropriate authorisation and pharmacist oversight.',['Prescription and dispensing workflow','Accuracy-checking roles and limits','Handling discrepancies and escalation'],'Task-specific training and observed competence.',psi],
 ['drugs',['Controlled','drugs'],'Controlled drugs handling and records',['Handle drugs safely','Keep records'],'Dispensary','Relevant dispensary staff','Apply the requirements for the medicine and the person’s authorised duties.',['Safe custody and access','Records and reconciliation','Discrepancies, returns and escalation'],'SOP acknowledgement and supervised competency record.',psi],
 ['storage',['Storage &','cold chain'],'Storage, cold chain, date checking and waste medicines',['Store safely','Manage your stock'],'Dispensary','Relevant dispensary staff','Use approved storage, excursion and waste procedures.',['Temperature monitoring and excursions','Stock rotation and expiry checks','Segregation and waste-medicine handling'],'Dated instruction and task-specific competency record.',psi],
 ['fmd',['FMD','scanning'],'Falsified Medicines Directive scanning and decommissioning',['Verify packs','Handle FMD alerts'],'Dispensary','Staff undertaking FMD tasks','Use the pharmacy’s approved FMD workflow.',['Verification and decommissioning','Alerts and escalation','Exceptions and approved records'],'System training and observed workflow competence.'],
 ['software',['Dispensing','software'],'Dispensing software',['Use your system','Work securely'],'Dispensary','Staff using dispensing software','Training is specific to the local system and authorised access.',['Role-based system access','Accurate entries and workflow','Error handling and support'],'System-specific training and competency record.'],
 ['cpd',['CPD &','ePortfolio'],'Continuing professional development',['Record your learning','Keep your ePortfolio'],'Pharmacists','Registered pharmacists','Maintain the statutory CPD ePortfolio. Annual ePortfolio Review starts in January 2027, subject to PSI eligibility and exemptions.',['Reflect on learning needs','Record CPD in the IIOP ePortfolio','Prepare for the applicable PSI review'],'CPD evidence remains in the designated IIOP ePortfolio.',cpd],
 ['vaccination',['Vaccination','services'],'Vaccination training',['Prepare safely','Deliver vaccinations'],'Pharmacists','Pharmacists providing vaccinations','Assign only where the service is offered; use current PSI-approved training requirements.',['Required approved training','Service preparation and vaccine knowledge','Practical competence and required updates'],'Current approved training evidence for the service.',vaccination],
 ['emergency',['Emergency','medicines'],'Emergency medicines training',['Emergency response','Medicine training'],'Pharmacists','Pharmacists providing the service','Use current PSI requirements for the emergency medicine service offered.',['Service-specific approved training','Recognise emergencies and escalation','Administration and required records'],'Approved service-specific training evidence.',vaccination],
 ['cpr',['CPR &','anaphylaxis'],'CPR and anaphylaxis management',['CPR skills','Anaphylaxis care'],'Pharmacists','Relevant service pharmacists','Competence and currency must meet the applicable service requirements.',['Approved CPR training and practical skills','Recognition and management of anaphylaxis','Emergency response and support'],'Required practical training and current certificate.',vaccination],
 ['services',['Clinical','services'],'Service-specific training',['Build your skills','For each service'],'Pharmacists','Pharmacists providing the service','Assign according to services offered, including opioid substitution where applicable.',['Service-specific procedures and competence','Patient assessment and referral boundaries','Required records and continuing updates'],'Training and competency evidence for each service.',psi],
 ['firstaid',['First aid','response'],'First aid responder',['Provide first aid','Get emergency help'],'Risk-based','Designated first aid responders','The risk assessment determines first-aid provision and designated staff.',['Approved responder training','Site first-aid equipment and arrangements','Emergency help and incident records'],'Appropriate responder certificate and local briefing.',safety],
 ['infection',['Infection','prevention'],'Sharps and infection prevention and control',['Prevent infection','Sharps safety'],'Risk-based','Staff exposed to the risk','Assign according to duties and services offered.',['Infection prevention and hygiene','Safe sharps handling and disposal','Exposure incidents and escalation'],'Risk-specific instruction and competency evidence.',safety],
 ['aggression',['Robbery &','aggression'],'Robbery and aggression',['Manage aggression','Respond to threats'],'Risk-based','Staff exposed to the risk','Use the site security risk assessment and response procedures.',['De-escalation and personal safety','Robbery and security response','Reporting and support after an incident'],'Risk-specific training and local security briefing.',safety],
 ['lone',['Lone','working'],'Lone working',['Work safely alone','Know who to call'],'Risk-based','Staff who work alone','Assign where lone working occurs and is permitted by local arrangements.',['Risk controls and check-in arrangements','Emergency contacts and escalation','Limits and unsafe situations'],'Local lone-working briefing and acknowledgement.',safety],
 ['chemical',['Chemical','safety'],'Chemical safety',['Safe chemical use','Exposure response'],'Risk-based','Staff handling hazardous chemicals','Assign according to chemicals used and the site risk assessment.',['Labels and safety data sheets','Storage, protective equipment and safe use','Spills, exposure and emergency response'],'Chemical-specific instruction and training record.',safety]
];
export const trainingCatalogue:TrainingModule[]=rows.map(([id,title,name,description,group,audience,condition,topics,evidence,source])=>({id,title,name,description,group,audience,condition,topics,evidence,source}));
